project_id = "zrzlzggixuogpxberdxt"

[functions.webhook-receiver]
verify_jwt = false

[functions.webhook-proxy]
verify_jwt = false

[functions.email-tracker]
verify_jwt = false

[functions.send-certificate]
verify_jwt = false
